name: flow1
on: 
  workflow_dispatch:
  #push:
  #  branches: [ "draft" ]
  #pull_request:
  #  branches: [ "draft" ]
  schedule:
    - cron: '0 22 * * 1-5'
    - cron: '0 */1 * * 1-5'

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!        

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          date +%Y%m%d_%H%M%S > report.txt
          git config user.name 'action'
          git config user.email 'action'
          git add report.txt
          git commit -am .
          git push
