name: draft0 flow1
on:
  # workflow_dispatch:
    #inputs:
    #  name:
    #    description: 'Person to greet'
    #    default: 'World'
    #    required: true
  # push:
  #   branches: [ "draft0" ]
  # pull_request:
  #   branches: [ "draft0" ]
  #schedule:
    ## - cron: '0 22 * * 1-5'
    ## - cron: '0 */1 * * 1-5'
    # - cron: '45 14 * * 1-5'
    # - cron: '15 21 * * 1-5'
    
permissions:
  contents: write
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: draft0

      #- name: Send greeting
      #  run: echo "Hello ${{ github.event.inputs.name }}"

      - name: Run a one-line script
        run: echo Hello, world!        

      - name: Run a multi-line script
        run: |
          # chmod +x ./scripts/flow1.sh
          # git commit -am .
          # git push
          
          #./scripts/flow1.sh
