name: draft0 flow1
on:
  # workflow_dispatch:
    #inputs:
    #  name:
    #    description: 'Person to greet'
    #    default: 'World'
    #    required: true
  push:
    branches: [ "draft0" ]
  pull_request:
    branches: [ "draft0" ]
  #schedule:
  #  - cron: '0 22 * * 1-5'
  #  - cron: '0 */1 * * 1-5'
    
permissions:
  contents: write
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: draft

      #- name: Send greeting
      #  run: echo "Hello ${{ github.event.inputs.name }}"

      - name: Run a one-line script
        run: echo Hello, world!        

      - name: Run a multi-line script
        run: |          
          set -x
          WD=$(date +%Y%m%d_%H%M%S)          
                    
          git branch
          git status
          git config user.name 'action'
          git config user.email 'action'
          
          echo $WD > report.txt
          git add report.txt
          git commit -am .
          git push
          
          git branch
          git status
          ls
          git sparse-checkout init --cone
          git sparse-checkout set .
          ls
          git status
          git fetch --depth 1 origin draft1
          git branch draft1 origin/draft1
          git checkout draft1
          ls
          git status
          
          echo WD: $WD
          mkdir $WD
          cd $WD
          echo $WD > report.txt
          ../flow1.sh
          
          git add $WD/report.txt --sparse
          git status
          git commit -am .
          git push origin draft1
          
          # git checkout draft
          # git status
